### ISSUE TITLE
Is there any plan to support Nuxt3?

### ISSUE THREAD

**Issue by itsmnthn** [Kapcash/ssr-class-serializer-module#1]

**Comment by Kapcash** [comment]
Hi!
No plan to support Nuxt 3 for the moment. I could take a look someday to implement it without relying on decorators (which are not really usable with Vue 3 since vue-class-decorator is not supported).

Any contribution is welcomed here! :)

**Comment by itsmnthn** [comment]
I've requested this feature via [#5207](https://github.com/nuxt/nuxt.js/issues/14058) on nuxt/framework repo and they have added enhancement label. Hoping to get native support.
