### ISSUE TITLE
Deserializing plain JS classes from SSR ?

### ISSUE THREAD

**Issue by CaptainFalcon92** [Kapcash/ssr-class-serializer-module#2]
Hello.

I do not use Typescript and do not plan to.
Still the problem exists with good old JS classes :

```js
    async fetch() {
      try {
        const res = await this.$axios.get('/orders')
        this.orders = res.data.map((obj) => Order.fromResponse(obj))
      } catch (e) {
        console.error(e)
      }
    },
```

Client side, this gives Order objects.
First load from SSR this gives plain JS anonymous objects.

It cannot support class methods or getters for that matter...
Any possibility to use your module for simple JS classes to ?

Thanks.

**Comment by Kapcash** [comment]
Sadly this module relies on Typescript decorators, with the usage of [vue-class-component](https://github.com/vuejs/vue-class-component). I'll try to think about another way of doing this, but it's not planned for the moment.

Any help is welcome! ;)
